3924: accept agreement
nhs-digital-gp-it-futures/AdminAcceptanceTests pull request #25
Opened 2020-04-30 10:43 UTC by talawson05

See the discussion comment in the step for the last scenario

2020-04-30 11:03 UTC, PhysicsJon requested changes

2020-04-30 11:03 UTC, PhysicsJon commented on src/AdminAcceptanceTests.Steps/Steps/Authorization/AcceptAgreement.cs
> +            new Authorization(Test, Context).ThenTheUserIsLoggedOut();
Should initialize Authorization once then use for both methods

2020-04-30 15:20 UTC, PhysicsJon approved these changes

2020-05-01 10:39 UTC, talawson05 commented
![image](https://user-images.githubusercontent.com/55191681/80800071-7314e980-8ba0-11ea-8262-70a4f8866eda.png)
Tests all passed locally

2020-05-01 10:40 UTC, merged